[package]
name = "oreui-designer"
version = "0.1.0"
description = "DearOreUI visual designer"
authors = []
edition = "2021"

[lib]
name = "oreui_designer_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
window-vibrancy = "0.6"
notify = "8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
